#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations


API_KEY_DEFAULT = ""
API_SECRET_DEFAULT = ""
EXCHANGE_PROXY_DEFAULT = ""
EXCHANGE_USE_CONFIG_PROXY_DEFAULT = False

SPOT_SYMBOL_DEFAULT = "BNBUSDT"
SPOT_ROUNDS_DEFAULT = 20
TRADE_ACCOUNT_TYPE_SPOT = "现货"
TRADE_ACCOUNT_TYPE_FUTURES = "合约"
TRADE_ACCOUNT_TYPE_OPTIONS = (
    TRADE_ACCOUNT_TYPE_SPOT,
    TRADE_ACCOUNT_TYPE_FUTURES,
)
TRADE_ACCOUNT_TYPE_DEFAULT = TRADE_ACCOUNT_TYPE_SPOT

TRADE_MODE_MARKET = "市价"
TRADE_MODE_CONVERT = "闪兑"
TRADE_MODE_LIMIT = "挂单"
TRADE_MODE_PREMIUM = "溢价单"
TRADE_MODE_OPTIONS = (
    TRADE_MODE_MARKET,
    TRADE_MODE_CONVERT,
    TRADE_MODE_LIMIT,
    TRADE_MODE_PREMIUM,
)
TRADE_MODE_DEFAULT = TRADE_MODE_MARKET

PREMIUM_DELTA_DEFAULT = ""
PREMIUM_ORDER_COUNT_DEFAULT = 0
PREMIUM_APPEND_THRESHOLD_DEFAULT = "0"
BNB_FEE_STOP_DEFAULT = ""
BNB_TOPUP_AMOUNT_DEFAULT = "0"
REPRICE_THRESHOLD_DEFAULT = "0"

FUTURES_SYMBOL_DEFAULT = "BTCUSDT"
FUTURES_ROUNDS_DEFAULT = 20
FUTURES_AMOUNT_DEFAULT = "100"
FUTURES_LEVERAGE_DEFAULT = 10
FUTURES_MARGIN_TYPE_CROSSED = "CROSSED"
FUTURES_MARGIN_TYPE_ISOLATED = "ISOLATED"
FUTURES_MARGIN_TYPE_LABEL_CROSSED = "全仓"
FUTURES_MARGIN_TYPE_LABEL_ISOLATED = "逐仓"
FUTURES_MARGIN_TYPE_OPTIONS = (
    FUTURES_MARGIN_TYPE_CROSSED,
    FUTURES_MARGIN_TYPE_ISOLATED,
)
FUTURES_MARGIN_TYPE_LABEL_OPTIONS = (
    FUTURES_MARGIN_TYPE_LABEL_CROSSED,
    FUTURES_MARGIN_TYPE_LABEL_ISOLATED,
)
FUTURES_MARGIN_TYPE_DEFAULT = FUTURES_MARGIN_TYPE_CROSSED
FUTURES_MARGIN_TYPE_VALUE_TO_LABEL = {
    FUTURES_MARGIN_TYPE_CROSSED: FUTURES_MARGIN_TYPE_LABEL_CROSSED,
    FUTURES_MARGIN_TYPE_ISOLATED: FUTURES_MARGIN_TYPE_LABEL_ISOLATED,
}
FUTURES_MARGIN_TYPE_LABEL_TO_VALUE = {
    FUTURES_MARGIN_TYPE_LABEL_CROSSED: FUTURES_MARGIN_TYPE_CROSSED,
    FUTURES_MARGIN_TYPE_LABEL_ISOLATED: FUTURES_MARGIN_TYPE_ISOLATED,
}
FUTURES_SIDE_LONG = "做多"
FUTURES_SIDE_SHORT = "做空"
FUTURES_SIDE_OPTIONS = (
    FUTURES_SIDE_LONG,
    FUTURES_SIDE_SHORT,
)
FUTURES_SIDE_DEFAULT = FUTURES_SIDE_LONG

WITHDRAW_ADDRESS_DEFAULT = ""
WITHDRAW_NETWORK_DEFAULT = "BSC"
WITHDRAW_COIN_DEFAULT = "USDT"
WITHDRAW_FEE_BUFFER_DEFAULT = 0
WITHDRAW_NETWORK_OPTIONS = (
    "BSC",
    "ETH",
    "TRX",
    "ARB",
    "OP",
    "MATIC",
    "AVAXC",
    "SOL",
    "BASE",
    "LINEA",
    "ZKSYNCERA",
)
WITHDRAW_COIN_OPTIONS = (
    "BNB",
    "USDT",
    "USDC",
)

MAX_THREADS_DEFAULT = 5

__all__ = [name for name in globals() if name.isupper()]
